FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
RUN npm install -g nodemon
#install jest and supertest
RUN npm install supertest
RUN npm install -g jest
COPY . .
CMD ["npm", "run", "dev"]
