name: Build and push dev image # Nom du workflow

on:
  push:
    branches:
      - dev

jobs:
  run-github-actions:
    runs-on: ubuntu-latest # Système d'exploitation du runner

    steps:
      - name: Checkout # Étape 1 : cloner le dépôt
        uses: actions/checkout@v1

      - name: Login to Docker Hub # Étape 2 : se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image # Étape 3 : construire l'image Docker
        run: docker image build -t yosrmd/simplewebdev-f -f Dockerfile.dev .

      - name: Push image # Étape 4 : pousser l'image sur Docker Hub
        run: docker image push yosrmd/simplewebdev-f

