name: Deploy Application Image

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy-app:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Étape 1 : Cloner le dépôt
        uses: actions/checkout@v1

      - name: Login to Docker Hub # Étape 2 : Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build production image # Étape 3 : Construire l'image de production
        run: docker image build -t yosrmd/simplewebprod .

      - name: Push production image # Étape 4 : Pousser l'image sur Docker Hub
        run: docker image push yosrmd/simplewebprod

      - name: Deploy App Render Container
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
        deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
        image-url: yosrmd/simplewebprod:latest
        render-api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-deployment: true
