name: Shell Commands # Nom du workflow

# Événement déclencheur du workflow
on:
  push:
    branches:
      - dev

jobs:
  run-shell-command: # Nom du job
    runs-on: ubuntu-latest # Système d'exploitation du runner

    steps:
      - name: Echo a string # Étape 1 : afficher un message
        run: echo "Starting"

      - name: Multiline script # Étape 2 : script sur plusieurs lignes
        run: |
          node -v
          npm -v # Notez l'espace entre 'npm' et '-v'

